### ISSUE TITLE
Cassandra connect sink failing:  A KCQL error occurred. Can't flatten from schema:Schema{MAP}

### ISSUE THREAD

**Issue by navd** [Landoop/avro-sql#2]
Hi,

I am trying to configure the Cassandra sink connector 
https://github.com/Landoop/stream-reactor/tree/master/kafka-connect-cassandra

My avro schema has one field as map
`{ "name": "desc", "type": {"type": "map", "values": "string"}}`

I am trying to map this to Cassandra column `description map<text,text>`, but getting the following issue.
Logs below.

```
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:559)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:315)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:218)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:186)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: A KCQL error occurred.Can't flatten from schema:Schema{MAP} by selecting 'desc'
	at com.datamountaineer.streamreactor.connect.errors.ThrowErrorPolicy.handle(ErrorPolicy.scala:58)
	at com.datamountaineer.streamreactor.connect.errors.ErrorHandler$class.handleError(ErrorHandler.scala:83)
	at com.datamountaineer.streamreactor.connect.errors.ErrorHandler$class.handleTry(ErrorHandler.scala:64)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter.handleTry(CassandraJsonWriter.scala:45)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter.insert(CassandraJsonWriter.scala:190)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter.write(CassandraJsonWriter.scala:137)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraSinkTask$$anonfun$put$2.apply(CassandraSinkTask.scala:69)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraSinkTask$$anonfun$put$2.apply(CassandraSinkTask.scala:69)
	at scala.Option.foreach(Option.scala:257)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraSinkTask.put(CassandraSinkTask.scala:69)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:537)
	... 10 more
Caused by: java.lang.IllegalArgumentException: A KCQL error occurred.Can't flatten from schema:Schema{MAP} by selecting 'desc'
	at com.datamountaineer.streamreactor.connect.converters.Transform$.raiseException$1(Transform.scala:40)
	at com.datamountaineer.streamreactor.connect.converters.Transform$.apply(Transform.scala:83)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter$$anonfun$4$$anonfun$apply$5$$anonfun$apply$1.apply$mcV$sp(CassandraJsonWriter.scala:161)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter$$anonfun$4$$anonfun$apply$5$$anonfun$apply$1.apply(CassandraJsonWriter.scala:160)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter$$anonfun$4$$anonfun$apply$5$$anonfun$apply$1.apply(CassandraJsonWriter.scala:160)
	at com.datamountaineer.streamreactor.connect.concurrent.ExecutorExtension$RunnableWrapper$$anon$1.run(ExecutorExtension.scala:30)
	... 3 more
Caused by: java.lang.IllegalArgumentException: Can't flatten from schema:Schema{MAP} by selecting 'desc'
	at com.landoop.connect.sql.StructSchemaSql$AvroSchemaExtension$.checkAllowedSchemas(StructSchemaSql.scala:346)
	at com.landoop.connect.sql.StructSchemaSql$SchemaSqlExtensions$$anonfun$com$landoop$connect$sql$StructSchemaSql$SchemaSqlExtensions$$createRecordSchemaForFlatten$extension$3.apply(StructSchemaSql.scala:183)
	at com.landoop.connect.sql.StructSchemaSql$SchemaSqlExtensions$$anonfun$com$landoop$connect$sql$StructSchemaSql$SchemaSqlExtensions$$createRecordSchemaForFlatten$extension$3.apply(StructSchemaSql.scala:136)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at com.landoop.connect.sql.StructSchemaSql$SchemaSqlExtensions$.com$landoop$connect$sql$StructSchemaSql$SchemaSqlExtensions$$createRecordSchemaForFlatten$extension(StructSchemaSql.scala:136)
	at com.landoop.connect.sql.StructSchemaSql$SchemaSqlExtensions$.flatten$extension(StructSchemaSql.scala:91)
	at com.landoop.connect.sql.StructSql$StructSqlConverter$$anonfun$sql$extension2$1.apply(StructSql.scala:85)
	at com.landoop.connect.sql.StructSql$StructSqlConverter$$anonfun$sql$extension2$1.apply(StructSql.scala:78)
	at scala.Option.map(Option.scala:146)
	at com.landoop.connect.sql.StructSql$StructSqlConverter$.sql$extension2(StructSql.scala:78)
	at com.datamountaineer.streamreactor.connect.converters.Transform$$anonfun$5.apply(Transform.scala:80)
	at com.datamountaineer.streamreactor.connect.converters.Transform$$anonfun$5.apply(Transform.scala:80)
	at scala.util.Try$.apply(Try.scala:192)
	at com.datamountaineer.streamreactor.connect.converters.Transform$.apply(Transform.scala:80)
	... 7 more
```

**Comment by ryaj** [comment]
Have almost the same. 
_"....Can't flatten from schema:Schema{ARRAY} by selecting 'vector'..."_
I tried to put in into vector list<text> column.

What about a solution?
